name: matrix build

on:
  pull_request:
    paths:
      - 'srcpkgs/**'
  repository_dispatch:
    types: [build]
  workflow_dispatch:
    inputs:
      all:
        description: 'Rebuild everything'
        required: false
        default: false
        type: boolean
      templates:
        description: 'Build multiple packages'
        required: false
        type: string
      template:
        description: 'Build single package'
        required: false
        type: choice
        default: ''
        options:
