name: matrix build

on:
  pull_request:
    paths:
      - 'srcpkgs/**'
  repository_dispatch:
    types: [build]
  workflow_dispatch:
    inputs:
      templates:
        description: 'Build multiple packages'
        required: false
        default: ""
        type: string
      template:
        description: 'Build single package'
        required: false
        default: ''
        type: choice
        options:
        -
