name: matrix build

on:
  #push:
  #  branches:
  #    - master
  #    - main
  #  paths:
  #    - 'srcpkgs/**'
  workflow_dispatch:
    description: 'If no package is selected, all templates in the branch will be compiled.'
    inputs:
      templates:
        description: 'Build multiple packages'
        required: false
        default: ""
        type: string
      template:
        description: 'Build single package'
        required: false
        default: ''
        type: choice
        options:
        -
