#!/bin/bash
case "$ACTION" in
post)
	if [ "$UPDATE" = "no" ]; then
		xdg-user-dirs-update
		layout=$(grep 'KEYMAP=' /etc/rc.conf | cut -d= -f2)
mkdir -p /usr/share/cosmic/com.system76.CosmicComp/v1/
touch /usr/share/cosmic/com.system76.CosmicComp/v1/xkb_config
cat >> /usr/share/cosmic/com.system76.CosmicComp/v1/xkb_config <<EOF
(
rules: "",
model: "",
layout: "us",
variant: "",
options: None,
repeat_delay: 600,
repeat_rate: 25,
)
EOF
		sed -i "s/us/$layout/" /usr/share/cosmic/com.system76.CosmicComp/v1/xkb_config
		if [ ! -h /usr/bin/firefox ]; then
			sed -i 's/firefox//' /usr/share/cosmic/com.system76.CosmicAppList/v1/favorites
		fi
		if [ ! -h /etc/xdg/autostart/pipewire.desktop ]; then
			mkdir -p /etc/xdg/autostart
			ln -s /usr/share/applications/pipewire.desktop /etc/xdg/autostart/
		fi

		mkdir -p /etc/pipewire/pipewire.conf.d
		if [ ! -h /etc/pipewire/pipewire.conf.d/10-wireplumber.conf ]; then
			ln -s /usr/share/examples/wireplumber/10-wireplumber.conf /etc/pipewire/pipewire.conf.d/
		fi
		if [ ! -h /etc/pipewire/pipewire.conf.d/20-pipewire-pulse.conf ]; then
			ln -s /usr/share/examples/pipewire/20-pipewire-pulse.conf /etc/pipewire/pipewire.conf.d/
		fi
	fi
	if [ "$UPDATE" = "yes" ]; then
		if [ -h /etc/xdg/autostart/pipewire-pulse.desktop ]; then
			rm /etc/xdg/autostart/pipewire-pulse.desktop
			if [ ! -h /etc/pipewire/pipewire.conf.d/20-pipewire-pulse.conf ]; then
	                        ln -s /usr/share/examples/pipewire/20-pipewire-pulse.conf /etc/pipewire/pipewire.conf.d/
 			fi
		fi
                if [ -h /etc/xdg/autostart/wireplumber.desktop ]; then
                        rm /etc/xdg/autostart/wireplumber.desktop
                        if [ ! -h /etc/pipewire/pipewire.conf.d/10-wireplumber.conf ]; then
                                ln -s /usr/share/examples/wireplumber/10-wireplumber.conf /etc/pipewire/pipewire.conf.d/
                        fi
                fi
	fi
	;;
esac
